### ISSUE TITLE
🐛 [Bug] Compiled on Ubuntu 22.04 with MySQL 5.7

### ISSUE THREAD

**Issue by Vanheden** [vmangos/core#1785]
## 🐛 Bug report
Getting this error on a fresh compiled core on Ubuntu 22.04 with MySQL 5.7
This happens when I try to login.

When I try to add **logon_db_updates.sql** I recieve this.

`ERROR 1067 (42000) at line 33: Invalid default value for 'last_login'`

```
`Accepting connection from 'IP'
[AuthChallenge] Account 'ADMIN' using IP 'IP' is using 'enUS' locale (0)
[AuthChallenge] Account 'ADMIN' using IP 'IP' successfully authenticated
SQL: UPDATE `account` SET `sessionkey` = 'DB4E25488DA0CEC287AB0EA1FFE7EF3B41C251642EBAF05EC08361553EB883BD78D8485C41B8ED6E', `last_ip` = 'IP', `last_login` = NOW(), `locale` = '0', `failed_logins` = 0, `os` = 'Win', `platform` = 'x86' WHERE `username` = 'ADMIN'
[1054] Unknown column 'platform' in 'field list'
Your database structure is not up to date. Please make sure you have executed all the queries in the sql/updates folders.
/home/roddan/vmangos/core/src/shared/Database/DatabaseMysql.cpp:183: Error: Assertion in HandleMySQLError failed: false
./realmd(+0x39457) [0x55b12a98b457]
./realmd(+0x323b7) [0x55b12a9843b7]
./realmd(+0x174d1) [0x55b12a9694d1]
./realmd(+0x14462) [0x55b12a966462]
./realmd(+0x1a795) [0x55b12a96c795]
/lib/x86_64-linux-gnu/libACE-7.0.6.so(_ZN20ACE_Dev_Poll_Reactor17dispatch_io_eventERNS_11Token_GuardE+0x2e7) [0x7f9b0cb12d27]
/lib/x86_64-linux-gnu/libACE-7.0.6.so(_ZN20ACE_Dev_Poll_Reactor13handle_eventsEP14ACE_Time_Value+0x1fe) [0x7f9b0cb14dfe]
/lib/x86_64-linux-gnu/libACE-7.0.6.so(_ZN11ACE_Reactor22run_reactor_event_loopER14ACE_Time_ValuePFiPS_E+0xd2) [0x7f9b0cb638c2]
./realmd(+0x135e0) [0x55b12a9655e0]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f9b0bb06d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f9b0bb06e40]
./realmd(+0x13a55) [0x55b12a965a55]

terminate called after throwing an instance of 'std::runtime_error'
  what():  false
Aborted (core dumped)`
```

### Steps to reproduce
Compile on Ubuntu 22.04 with MySQL 5.7

### Version & Environment
Client Version: 1.12.1.5875
Commit Hash:  32ca056b781be52d59b82acdf2aff3ce58633677

OS Client: Windows 10
OS Server: Ubuntu 22.04 Server

**Comment by ratkosrb** [comment]
https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at

**Comment by Vanheden** [comment]
> https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at

Thank you !

**Comment by samuel-edmund-morgan** [comment]
Excatly same errors. Provided link didn't help

**Comment by ratkosrb** [comment]
@samuel-edmund-morgan Try installing MySQL 5.5 and you shouldn't get the error.
