### PR TITLE
Fix nesting of free().

### PR DESCRIPTION
**Pull request by mserajnik**
## 🍰 Pullrequest
This fixes the GCC/Clang build error:
```
/home/runner/work/core/core/src/mangosd/CliRunnable.cpp: In member function ‘void CliRunnable::operator()()’:
/home/runner/work/core/core/src/mangosd/CliRunnable.cpp:128:14: error: ‘command_str’ was not declared in this scope
  128 |         free(command_str);
      |              ^~~~~~~~~~~
[ 99%] Building CXX object src/mangosd/CMakeFiles/mangosd.dir/MaNGOSsoap.cpp.o
make[2]: *** [src/mangosd/CMakeFiles/mangosd.dir/build.make:76: src/mangosd/CMakeFiles/mangosd.dir/CliRunnable.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:556: src/mangosd/CMakeFiles/mangosd.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

The new `if (s_canReadLine)` introduced in https://github.com/vmangos/core/commit/79c5f503df39cd92eccc399443f8502eb8f9c248 probably caused the auto-merge to fuck up the nesting.

The PR also makes it so `free()` is used on Windows as well; when #2572 was opened, readline support didn't exist on Windows, but now it does (so the `free()` needs to happen there as well).

### Proof

- None

### Issues

- None

### How2Test

- None

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by mserajnik** [comment]
But I just realized, since https://github.com/vmangos/core/commit/79c5f503df39cd92eccc399443f8502eb8f9c248 introduced readline support for Windows, the `free()` should probably happen on Windows as well?

**Comment by imranh2** [comment]
Yep, we should do an unconditional free, just remove the preprocessor ifdefs

**Comment by mserajnik** [comment]
> Yep, we should do an unconditional free, just remove the preprocessor ifdefs

Yeah, I didn't realize this at first because I was only focused on the wrong nesting. 😄 
I adjusted this PR now.
